apiVersion: v2
name: pqueue
description: Helm chart for the pqueue API service
type: application
version: 0.2.1
appVersion: "0.2.1"
keywords:
  - pqueue
  - queue
  - kubernetes
maintainers:
  - name: pqueue maintainers
