{{- if and (or (and (eq .Values.storage.log.backend "objectlog") (eq .Values.storage.log.objectLog.store "local")) (eq .Values.storage.projection.backend "sqlite") (eq .Values.storage.projection.backend "turso") (eq .Values.storage.projection.backend "hybrid") (eq .Values.storage.projection.backend "hybrid-async")) .Values.persistence.enabled (not .Values.persistence.existingClaim) -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "fireweed-queue.storagePvcName" . }}
  labels:
    {{- include "fireweed-queue.labels" . | nindent 4 }}
  {{- with .Values.persistence.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  accessModes:
    {{- toYaml .Values.persistence.accessModes | nindent 4 }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
  {{- if .Values.persistence.storageClass }}
  storageClassName: {{ .Values.persistence.storageClass | quote }}
  {{- end }}
{{- end }}
