apiVersion: v1
kind: Service
metadata:
  name: {{ include "fireweed-queue.fullname" . }}
  labels:
    {{- include "fireweed-queue.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: resp
      port: {{ .Values.service.port }}
      targetPort: resp
      protocol: TCP
  selector:
    {{- include "fireweed-queue.selectorLabels" . | nindent 4 }}
