apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "pqueue.fullname" . }}-config
  labels:
    {{- include "pqueue.labels" . | nindent 4 }}
data:
  PQUEUE_LISTEN_ADDR: {{ .Values.config.listenAddr | quote }}
  PQUEUE_LOG_BACKEND: {{ .Values.storage.log.backend | quote }}
  PQUEUE_PROJECTION_BACKEND: {{ .Values.storage.projection.backend | quote }}
  PQUEUE_PRINCIPAL_ID: {{ .Values.config.principalId | quote }}
  PQUEUE_TENANTS: {{ join "," .Values.config.tenants | quote }}
  PQUEUE_BOOTSTRAP_QUEUES: "t1:q1"
  PQUEUE_SHARD_COUNT_MIN: {{ .Values.storage.shardCount.min | quote }}
  PQUEUE_SHARD_COUNT_MAX: {{ .Values.storage.shardCount.max | quote }}
  {{- if eq .Values.storage.log.backend "objectlog" }}
  PQUEUE_OBJECT_LOG_ROOT: {{ .Values.storage.log.objectLog.root | quote }}
  {{- end }}
  {{- if eq .Values.storage.projection.backend "sqlite" }}
  PQUEUE_SQLITE_PROJECTION_PATH: {{ .Values.storage.projection.sqlite.path | quote }}
  {{- end }}
