apiVersion: v1
kind: Secret
metadata:
  name: fireweed-postgres
type: Opaque
stringData:
  database-url: postgres://fireweed:fireweed@postgres:5432/fireweed
---
apiVersion: v1
kind: Secret
metadata:
  name: fireweed-object-log
type: Opaque
stringData:
  access-key-id: minioadmin
  secret-access-key: minioadmin
