apiVersion: v1
kind: Secret
metadata:
  name: pqueue-postgres
type: Opaque
stringData:
  database-url: postgres://pqueue:pqueue@postgres:5432/pqueue
---
apiVersion: v1
kind: Secret
metadata:
  name: pqueue-object-log
type: Opaque
stringData:
  access-key-id: minioadmin
  secret-access-key: minioadmin
