[package]
name = "pqueue-service"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
axum = "0.8"
pqueue-client = { path = "../pqueue-client" }
pqueue-core = { path = "../pqueue-core" }
pqueue-postgres = { path = "../pqueue-postgres" }
pqueue-storage = { path = "../pqueue-storage" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sha2 = "0.11"

[lib]
path = "src/lib.rs"

[dev-dependencies]
pqueue-objectlog = { path = "../pqueue-objectlog" }
pqueue-sqlite = { path = "../pqueue-sqlite" }
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
tokio-postgres = { version = "0.7", features = ["with-serde_json-1", "with-time-0_3"] }
tower = { version = "0.5", features = ["util"] }
